imagePullSecrets:
  - name: gitlab-registry-secret
  - name: harbor-registry-secret

replicaCount: 1
replicas: 1

livenessProbe:
  httpGet:
    path: /liveness
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 80
    protocol: TCP
  - name: https
    containerPort: 443
    protocol: TCP

# TODO
resources:
  requests:
    memory: "50Mi"
    cpu: "50m"
  limits:
    memory: "100Mi"
    cpu: "100m"

service:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https

ingress:
  enabled: true
  objects:
  - servicePort: 443
    # annotations:
    #   nginx.ingress.kubernetes.io/rewrite-target: /$2 #  1
    hosts:
    - name: {{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}
      # path: /{{ .Helm.Release.Name }}(/|$)(.*) #  1
#    tls:
#    - secretName: secret
#      hosts:
#        - {{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}
