environment: prod-dp

env:
  ENVIRONMENT: prod
  VITE_API_URL: https://autohiring.wildberries.ru
  VITE_API_URL_AUTH: https://auth-autohiring.wildberries.ru

ingress:
  enabled: true
  objects:
  - servicePort: 443
    hosts:
    - name: {{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}
    - name: autohiring.wildberries.ru
    - name: ah.wb.ru
